# -*- coding: utf-8 -*-
"""Design_of_AI_Lab_15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUTscufkAx-FmLOKlfmmNKFzERki-A87
"""

import pandas as pd
import tensorflow as tf
from tf.keras.datasets import cifar10
from tf.keras.models import Sequential
from tf.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense
from tf.keras.utils import to_categorical

(X_train,y_train),(X_test,y_test)=cifar10.load_data()
X_train=X_train/255.0
X_test=X_test/255.0
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

#define the model architecture
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3)))
model.add(MaxPooling2D((2,2)))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,batch_size=10,verbose=1)

_,acc=model.evaluate(X_test,y_test)

from sklearn.metrics import roc_auc_score
y_pred=model.predict(X_test)
print(roc_auc_score(y_test,y_pred))